# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

name: CI

on: [push]

jobs:
  test:
    name: Install Raylib
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["4.0.0"]
        toolchain: [stable, beta]
    steps:
      - name: Git clone raylib
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: raysan5/raylib
          path: raylib
          ref: ${{ matrix.version }}
      - name: Install packages
        run: sudo apt install -y cmake build-essential libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
      - name: Build raylib
        run: cd raylib && mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=ON .. && make && sudo make install

      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install ${{ matrix.toolchain }} toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # v1.0.6
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.1
        with:
          command: check

      - name: Run cargo test
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b # v1.0.1
        with:
          command: test
