# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

name: CI

on: [push]

jobs:
  test:
    name: Install Raylib
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["4.0.0"]
        toolchain: [stable, beta]
    steps:
      - name: Git clone raylib
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: raysan5/raylib
          path: raylib
          ref: ${{ matrix.version }}
      - name: Install packages
        run: sudo apt install -y cmake build-essential libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
      - name: Build raylib
        run: cd raylib && mkdir build && cd build && cmake -DBUILD_SHARED_LIBS=ON .. && make && sudo make install

      - name: Checkout sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - run: rustup update ${{ matrix.toolchain }}
      - run: rustup default ${{ matrix.toolchain }}
      - name: Run cargo check
        run: cargo check
      - name: Run cargo test
        run: cargo test
